# Site wide configuration

title:            Sander Wubben
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Sander Wubben
  avatar: https://pbs.twimg.com/profile_images/1296031243/eightbit-a5e4c942-d100-4d84-be15-ed3c1337ba42_400x400.png
  bio: "Assistant Professor in Computational Linguistics and Natural Language Generation."
  email: s.wubben@uvt.nl
  disqus-shortname: 
  twitter: swubbb
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: swubb
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: swubb
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: wubboomstam

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
